# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mintool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(max_length=200)),
                ('org_name', models.CharField(max_length=200)),
                ('gene_org', models.CharField(max_length=200)),
            ],
        ),
    ]
